name: Build and Deploy

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build & Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}:latest
            ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.sha }}

  deploy:
    name: Deploy to Server
    needs: build-and-push
    runs-on: ubuntu-latest
    # only deploy on pushes to main, not on PRs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to GCP VM via IAP tunnel
        run: |
         echo "${{ secrets.GCP_DEPLOY_SSH_KEY }}" > /tmp/deploy_key
         chmod 600 /tmp/deploy_key
         ssh-keygen -y -f /tmp/deploy_key > /tmp/deploy_key.pub
         gcloud compute ssh ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_INSTANCE_NAME }} \
          --zone=${{ secrets.GCP_ZONE }} \
          --tunnel-through-iap \
          --ssh-key-file=/tmp/deploy_key \
          --command="
            echo '${{ secrets.CR_PAT }}' | docker login ghcr.io -u masha-el --password-stdin
            cd ${{ secrets.GCP_VM_BOT_DIR }} &&
            docker compose pull &&
            docker compose up -d --remove-orphans &&
            docker image prune -f
          "